name: CI

on: push

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Test
        run: mvn clean test

  verify:
    needs: test
    
    name: Verify
    runs-on: ubuntu-latest

    steps:
      - uses: action/checkout@v2

      - uses: action/setup-java@v2
        with:
          java-version: 1.8

      - name: Verify
        run: mvn clean verify
